# docker-compose.yml
#
# This docker-compose file starts the following services:
#   - Flask container

#version: '3.8'
services:

  flask:
    image: mivalov/flask-py:3.10.6
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask-py
    hostname: flask-py
    environment:
      - TZ=Europe/Berlin
    ports:
      - target: 5000
        published: 5000
        protocol: tcp
        mode: host
    volumes:
      - type: bind
        source: ./rwdp
        target: /rwdp
    restart: always
